### PR TITLE
Warnings for REMOVED_LOCALES already defined : fixed #1757

### LINKED ISSUE #1757: Warnings for REMOVED_LOCALES already defined
##### Sharetribe Version:

80a0a888

##### Environment:

OSX

##### Server mode:

Development

##### Description:

There is a warning on every sql update every:

DEBUG   SQL (0.9ms)  UPDATE `delayed_jobs` SET `delayed_jobs`.`locked_at` = ...
/sharetribe/config/routes.rb:52: warning: already initialized constant REMOVED_LOCALES
/sharetribe/config/routes.rb:52: warning: previous definition of REMOVED_LOCALES was here
DEBUG   SQL (0.9ms)  UPDATE `delayed_jobs` SET `delayed_jobs`.`locked_at` =

##### Steps To Reproduce:

rake jobs:work

### PR DESCRIPTION
**Pull request by vtorves**
When executed using Mac OS X
`bundle exec rake jobs:work`
show messages:
```
Users/vtorves/Projects/sharetribe/config/routes.rb:50: warning: already initialized constant REMOVED_LOCALES
/Users/vtorves/Projects/sharetribe/config/routes.rb:50: warning: previous definition of REMOVED_LOCALES was here
```
fixed #1757

### CODE REVIEW

File: config/routes.rb [hunk 1]
```diff
@@ -47,7 +47,7 @@
     get "/check_email_availability" => "marketplaces#check_email_availability"
   end
 
-  REMOVED_LOCALES = Rails.application.config.REMOVED_LOCALES.to_a
+  REMOVED_LOCALES ||= Rails.application.config.REMOVED_LOCALES.to_a
```
Comment (rap1ds) [inline config/routes.rb]: I'd say the `REMOVED_LOCALES` is a bit unnecessary here. It's used only once in this file (line 52), so we could get rid of this variable assignment.

The `Rails.application.config.REMOVED_LOCALES` is assigned to `Sharetribe::REMOVED_LOCALES` in `application.rb`. The `Sharetribe::REMOVED_LOCALES` is defined in `available_locales.rb`.

So in the line 52, we could use the `Sharetribe::REMOVED_LOCALES`, like this:

```ruby
locale_matcher = Regexp.new(Sharetribe::AVAILABLE_LOCALES.map { |l| l[:ident] }.concat(Sharetribe::REMOVED_LOCALES).join("|"))
```

Does it make sense? Would you mind removing the `REMOVED_LOCALES` and using the `Sharetribe::AVAILABLE_LOCALES` instead?

**Comment by rap1ds** [comment]
@vtorves Thanks for the PR! I added one comment.

**Comment by vtorves** [comment]
@rap1ds make more sense!
I go update the code now. 
thanks to review and learning.

**Comment by vtorves** [comment]
@rap1ds Did i do something wrong?

**Comment by rap1ds** [comment]
@vtorves The code looks good! Thanks for the changes!

Can you still clean up the branch? [We don't accept pull requests with merge commits](CONTRIBUTING.md).

Are you familiar with `git rebase`? If not, here's a quick tip: you can use `git rebase -i <your-sharetribe-origin-remove>/master`. You can then squash the two commits to one and remove the merge commit.

**Comment by rap1ds** [comment]
@vtorves Thanks for the fix!
